# auth-template.yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MoneyGrab Mono-Repo Lambda Functions

Globals:
  Function:
    Runtime: java21
    Timeout: 10   # seconds
    MemorySize: 512

Resources:
  AuthLambdaFunction:
    Type: AWS::Serverless::Function
    DeletionPolicy: Delete
    Properties:
      FunctionName: moneygrab-groupAuthorizer
      Runtime: java21
      Handler: com.moola.fx.moneychanger.auth.functions.MoneyGrabGroupAuthorizer::handleRequest
      CodeUri: auth-lambda/
      Role: arn:aws:iam::797226340575:role/lambda-jwt-authorizer-role

Outputs:
  AuthLambdaArn:
    Description: ARN of the Auth Lambda
    Value: !GetAtt AuthLambdaFunction.Arn 