name: CD — Auth Lambda

on:
  push:
    branches: [ main ]
    # only run when auth-lambda code or the SAM template changes
    paths:
      - 'auth-lambda/**'
      - 'template.yml'

jobs:
  deploy-auth-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: '1.141.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: SAM build & deploy
        run: |
          sam build \
            --template-file template.yml \
            --build-dir .aws-sam/build
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name moneygrab-auth-stack \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM
