name: CD — Moneygrab Lambda

on:
  push:
    branches: [ main ]
    # only run when lambda code or the SAM template changes
    paths:
      - 'auth-lambda/**'
      - 'rate-lambda/**'
      - 'auth-template.yml'
      - 'rate-template.yml'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      auth_changed: ${{ steps.filter.outputs.auth }}
      rate_changed: ${{ steps.filter.outputs.rate }}
    steps:
      - uses: actions/checkout@v4

      - name: Detect changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            auth:
              - 'auth-lambda/**'
              - 'template.yml'
            rate:
              - 'rate-lambda/**'
              - 'rate-template.yml'

  deploy-auth-lambda:
    needs: detect-changes
    if: needs.detect-changes.outputs.auth_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Install & build full Maven project
        # Installs your parent POM and all modules into ~/.m2
        run: mvn clean install -DskipTests

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          version: '1.141.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: SAM build & deploy
        run: |
          sam build \
            --template-file auth-template.yml \
            --build-dir .aws-sam/build
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name moneygrab-auth-stack \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --s3-bucket moneygrab-codedeploy-artifacts \
            --s3-prefix moneygrab-functions \
            --no-fail-on-empty-changeset 
          

  deploy-rate-lambda:
    needs: detect-changes
    if: needs.detect-changes.outputs.rate_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Validate SAM Template
        run: sam validate --region ap-southeast-1

      - name: Build and Deploy RateLambdaFunction
        run: |
          sam build --template-file rate-template.yml
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name moneygrab-rate-stack \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM \
            --s3-bucket moneygrab-codedeploy-artifacts \
            --s3-prefix moneygrab-functions \
            --no-fail-on-empty-changeset 

