# .github/workflows/cd.yml
name: CI/CD — Auth Lambda

on:
  push:
    branches: [ main ]
    # only run when auth-lambda code or the SAM template changes
    paths:
      - 'auth-lambda/**'
      - 'template.yml'

jobs:
  deploy-auth-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Build auth-lambda JAR
        run: mvn clean package -pl auth-lambda -am -DskipTests

      - name: Install AWS SAM CLI
        run: sudo pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # replace with your GitHub-OIDC–IAM role
          role-to-assume: arn:aws:iam::123456789012:role/GithubActionsDeployRole
          aws-region: ap-southeast-1

      - name: SAM build & deploy
        run: |
          sam build \
            --template-file template.yml \
            --build-dir .aws-sam/build
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name moneygrab-auth-stack \
            --no-confirm-changeset \
            --capabilities CAPABILITY_IAM
